services:
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - LANYARD_API_URL=${LANYARD_API_URL:-https://api.lanyard.rest/v1}
      - BASE_URL=${BASE_URL:-https://lanyard.cnrad.dev}

volumes:
  redis_data:
    driver: local


# networks...
# use isolated mode in dokploy.